version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pactivas-prod:latest
    container_name: pactivas-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    networks:
      - pactivas-network

networks:
  pactivas-network:
    driver: bridge
